# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20190306_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
